-- MySQL Script generated by MySQL Workbench
-- Thu Jun 19 14:14:26 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ruaj
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ruaj` ;

CREATE SCHEMA IF NOT EXISTS `ruaj` DEFAULT CHARACTER SET utf8 ;
USE `ruaj` ;

-- -----------------------------------------------------
-- Table `categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `categorias` ;

CREATE TABLE IF NOT EXISTS `categorias` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nombre_cat` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_categoria`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Producto` ;

CREATE TABLE IF NOT EXISTS `Producto` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `nombre_prod` VARCHAR(45) NOT NULL,
  `precio` INT NOT NULL,
  `descripcion` TEXT NOT NULL,
  `foto` VARCHAR(255) NULL,
  `foto_alt` VARCHAR(255) NULL,
  `id_categoria` INT NOT NULL,
  PRIMARY KEY (`id_producto`),
  CONSTRAINT fk_categoria FOREIGN KEY (`id_categoria`) REFERENCES `categorias`(`id_categoria`)
) ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
